In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

In [5]:
df = pd.read_csv('/Users/madeleine/ml-poc-project/data/raw/natl2018us.csv', nrows=100000)

In [ ]:
df.columns.tolist(
    
)

In [ ]:
colonnes_a_garder = [
    'mager',      # Âge de la mère
    'bmi',        # Indice de masse corporelle
    'cig_0',      # Tabac avant grossesse
    'cig_1',      # Tabac 1er trimestre
    'precare',    # Début du suivi prénatal
    'wic',        # Aide alimentaire WIC
    'rf_phype',   # Hypertension préexistante
    'rf_pdiab',   # Diabète préexistant
    'pay',        # Assurance santé
    'wtgain',     # Prise de poids
    'ab_nicu'     # Notre variable cible (NICU)
]

# 2. Chargement optimisé
# J'ai repris le chemin exact de ton erreur précédente
chemin_fichier = '/Users/madeleine/ml-poc-project/data/raw/natl2018us.csv' 
df = pd.read_csv(chemin_fichier, usecols=colonnes_a_garder, nrows=100000)

# 3. Préparation de la Target (Nettoyage des données inconnues)
# On filtre pour garder uniquement les 'Y' et 'N'
df = df[df['ab_nicu'].isin(['Y', 'N'])].copy()

# On convertit en 1 (Risque) et 0 (Pas de risque)
df['Target_Risk'] = df['ab_nicu'].map({'Y': 1, 'N': 0})

# On supprime l'ancienne colonne texte
df = df.drop(columns=['ab_nicu'])

# 4. Affichage du résultat
print(f"Succès total ! Le dataset est chargé avec {df.shape[0]} lignes et {df.shape[1]} colonnes.\n")
display(df.head())

Succès total ! Le dataset est chargé avec 99900 lignes et 11 colonnes.

,mager,precare,wic,cig_0,cig_1,bmi,wtgain,rf_pdiab,rf_phype,pay,Target_Risk
0,30,3,N,0,0,30.7,41,N,N,2,0
1,35,3,N,2,2,33.3,0,N,N,1,1
2,28,5,Y,0,0,30.0,58,N,Y,5,0
3,23,5,N,0,0,23.7,0,N,N,1,0
4,37,5,Y,0,0,35.5,0,N,N,1,1

In [13]:
dictionnaire_renommage = {
    'mager': 'Age_Mere',
    'bmi': 'IMC_Mere',
    'cig_0': 'Tabac_Avant_Grossesse',
    'cig_1': 'Tabac_Trim1',
    'precare': 'Mois_Debut_Suivi',
    'wic': 'Aide_Sociale_WIC',
    'rf_phype': 'Hypertension_Chronique',
    'rf_pdiab': 'Diabete_Chronique',
    'pay': 'Type_Assurance',
    'wtgain': 'Prise_Poids_Lbs'
    # 'Target_Risk' est déjà très clair pour la modélisation, on le garde tel quel !
}

# 2. Application du renommage sur notre DataFrame
df = df.rename(columns=dictionnaire_renommage)

# 3. Vérification du résultat
print("Les nouvelles colonnes sont :")
print(df.columns.tolist())
display(df.head())

Les nouvelles colonnes sont :
['Age_Mere', 'Mois_Debut_Suivi', 'Aide_Sociale_WIC', 'Tabac_Avant_Grossesse', 'Tabac_Trim1', 'IMC_Mere', 'Prise_Poids_Lbs', 'Diabete_Chronique', 'Hypertension_Chronique', 'Type_Assurance', 'Target_Risk']

,Age_Mere,Mois_Debut_Suivi,Aide_Sociale_WIC,Tabac_Avant_Grossesse,Tabac_Trim1,IMC_Mere,Prise_Poids_Lbs,Diabete_Chronique,Hypertension_Chronique,Type_Assurance,Target_Risk
0,30,3,N,0,0,30.7,41,N,N,2,0
1,35,3,N,2,2,33.3,0,N,N,1,1
2,28,5,Y,0,0,30.0,58,N,Y,5,0
3,23,5,N,0,0,23.7,0,N,N,1,0
4,37,5,Y,0,0,35.5,0,N,N,1,1

In [14]:
from skrub import TableReport

TableReport(df)

Processing column  11 / 11